# Generated by Django 4.1.6 on 2023-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='response',
            field=models.CharField(default='Hello too', max_length=255),
        ),
    ]
